// Code generated by "stringer -type=ServiceState state_manager.go"; DO NOT EDIT.

package service_start

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceExited-0]
	_ = x[ServiceStarting-1]
	_ = x[ServiceRunning-2]
	_ = x[ServiceInShutdown-3]
	_ = x[ServiceError-4]
}

const _ServiceState_name = "ServiceExitedServiceStartingServiceRunningServiceInShutdownServiceError"

var _ServiceState_index = [...]uint8{0, 13, 28, 42, 59, 71}

func (i ServiceState) String() string {
	if i < 0 || i >= ServiceState(len(_ServiceState_index)-1) {
		return "ServiceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServiceState_name[_ServiceState_index[i]:_ServiceState_index[i+1]]
}
